Test-Driven Development
omermadmon/my-step-portfolio pull request #6
Opened 2020-09-08 11:12 UTC by omermadmon

This PR will focus on fixing and optimizing the portfolio project, as well as working on a separated calendar project as part of the last week of the training, focusing on TDD.
 
* Calendar project (TDD):
  * Write query logic to pass existing tests (for mandatory attendees only).
  * Add some more tests for optional attendees feature (including optional attendees when possible).
  * Expand query logic by passing those tests.
* Portfolio project:
  * Create a single class-wide DatastoreService field instead of creating a new instance of DatastoreService just-in-time (in each relevant servlet class).
  * Add comment and achievement constructors to get a datastore entity rather than each field separately.

2020-09-08 12:16 UTC, nolaviz requested changes

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/intro/src/test/java/com/google/sps/GreeterTest.java
> +  @BeforeClass
In tests, recommended practice *encourages* repetition - it's preferred that each testcase include its own setup ("arrange" section), invoke the method under test ("act" section), and perform any required assertions.
This way, each testcase can be read on its own, without needing to refer elsewhere to understand why it works.

@Before (or @BeforeClass) should be used only for setting up global "scaffolding", not relevant to the code under test itself: e.g., you may use these to start a database service, which the class under test then uses.

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/intro/src/test/java/com/google/sps/GreeterTest.java
> +    Assert.assertEquals("Hello Ada", greeting);
Google unit-test practices recommend to use Truth (https://truth.dev) rather than JUnit assertions.

Truth assertions are more "fluent", have fewer corner-cases, and print out better error messages.

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/intro/src/test/java/com/google/sps/GreeterTest.java
> +  // Whitespace should be trimmed
The testcase name already says this; no need to have a comment as well.
(Google style recommendation is to avoid comments unless there really is no way to express the same in code: experience shows that engineers will evolve the code and leave obsolete comments behind.)

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    // if there duration is longer than a day, return an empty list
"there duration" --> "the dueation"?

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    // if there are no events or no (non-optional) attendees, return {@code TimeRange.WHOLE_DAY} as a list
Is this special-case logic really needed? Won't the logic below return the same result anyway?

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    /** create two lists: one for time ranges of relevant events w.r.t all attendees,
Avoid using JavaDoc-style comments (`/** ... */`) inside code. Prefer to use multiple `//`-style comments.

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    ArrayList<ArrayList<TimeRange>> relevantTimeRangesLists =
Instead of using this nested structure, consider just having a simple method that returns a single list - and just invoke it twice (once with all attendees, once with only mandatory ones).

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    Collection<TimeRange> avilableTimeRangesAll =
Typo ("avilable" -> "available")

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +                FindMeetingQuery.filterIrrelevantTimesRanges(events, allAttendees, mandatoryAttendees);
No need to include the class name here (the method is in the same class as the caller).

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +                FindMeetingQuery.filterIrrelevantTimesRanges(events, allAttendees, mandatoryAttendees);
(same applies further down as well)

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      for (String requestedAttendee : attendees) {
Collections.disjoint() is your friend. No need to reinvent it here :-)

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      // init start and end of the next avilable slot (to add to result).
Typo: avilable -> available

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +          if (meetingDuration <= end - start) {
Can you just use TimeRange.overlaps()?

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +
No need for more than one blank line.

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +    Collection<TimeRange> expected =
Prefer to have a blank line here: line 303 is the "act" section, while 304 more properly belongs with the assertion phase.

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +    // The gap should be identified and retuned.
Typo: returned.

2020-09-08 12:16 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +
Remove unnecessary blank lines.

2020-09-08 13:04 UTC, omermadmon commented on portfolio/src/main/java/com/google/sps/data/Achievement.java
> +  public Achievement(Entity entity) {
Done.

2020-09-08 13:05 UTC, omermadmon commented on portfolio/src/main/java/com/google/sps/data/Comment.java
> +  public Comment(Entity entity) {
Done.

2020-09-08 13:27 UTC, omermadmon commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    // if there are no events or no (non-optional) attendees, return {@code TimeRange.WHOLE_DAY} as a list
Result should be the same, but I find it more efficient this way (I'd rather recognize it as an edge case than perform the whole query logic just to find out what was clear from the beginning).

2020-09-08 13:46 UTC, omermadmon commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    ArrayList<ArrayList<TimeRange>> relevantTimeRangesLists =
I find it more efficient this way, because this way I am iterating through events just once.

Asymptotically speaking, the runtime complexity analysis would be the same. However, if in the future we will have not only two level of attendence (mandatory and optional), but N levels, than reducing these iteration sounds like a good idea.

2020-09-08 13:56 UTC, omermadmon commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      for (String requestedAttendee : attendees) {
howMuchILoveJavaNow++;

2020-09-09 06:33 UTC, omermadmon commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +          if (meetingDuration <= end - start) {
I guess this should work:

```java
if (TimeRange.fromStartEnd(start, end, false).duration() >= meetingDuration)
```

But it is much less readable in my opinion. Did you think of a more elegant way?

2020-09-10 08:14 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    // if there are no events or no (non-optional) attendees, return {@code TimeRange.WHOLE_DAY} as a list
I'm not sure I agree about the efficiency concern: I usually recommend to only optimize when (or if) you actually see a performance issue. The special-case logic has additional costs (e.g., if I now change the decision logic, the special-case may become incorrect - not likely in this particular case, but not impossible.)

So - this is OK, but IMO not ideal.

2020-09-10 08:14 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    ArrayList<ArrayList<TimeRange>> relevantTimeRangesLists =
Efficiency is a distant second concern to code clarity. I really prefer that the code be simpler - if an optimization complicates the code (which you do here), we might avoid it even at the cost of paying more for resources.

2020-09-10 08:14 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +  private static ArrayList<ArrayList<TimeRange>> filterIrrelevantTimesRanges(Collection<Event> events, Collection<String> allAttendees, Collection<String> mandatoryAttendees) {
Note - Google code style recommends a column limit of 100: https://google.github.io/styleguide/javaguide.html#s4.4-column-limit

2020-09-10 08:14 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +          if (meetingDuration <= end - start) {
I actually see the alternative as more readable, mainly because it's obvious that both sides are durations.
But - your call.

2020-09-10 12:34 UTC, omermadmon commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    // if there are no events or no (non-optional) attendees, return {@code TimeRange.WHOLE_DAY} as a list
Thanks for this comment, will take these considerations into account next time. 
Fixed.

2020-09-10 12:53 UTC, omermadmon commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +          if (meetingDuration <= end - start) {
Done.

2020-09-10 12:57 UTC, omermadmon commented on portfolio/src/main/java/com/google/sps/data/Achievement.java
> +  * Is being used whenever an achievement object has to be created manually.
Fixed in both Comment and Achievement classes.

2020-09-10 13:14 UTC, nolaviz approved these changes

2020-09-10 13:14 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    Collections.sort(relevantTimeRangesAll, TimeRange.ORDER_BY_START);
Consider folding the sorting into filterIrrelevantTimesRanges (or, alternatively, into findAvailableTimeRanges).
Performing the sort here assumes use of mutable containers, which is against best practices (go/ej3e-17). Also - it's not clear if you're sorting because findAvailableTimeRanges requires it (it has no documentation to say so) or just because you want the output to look nice.

2020-09-10 13:14 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +          if (FindMeetingQuery.isRelevant(event, attendees)) relevantTimeRanges.add(event.getWhen());
No need to call out the class name for a method in the same class.

2020-09-10 13:14 UTC, nolaviz commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      for (Event event : events) {
You can simplify this loop using Java8 streams:

  List<TimeRange> relevantTimeRanges = events.stream()
      .filter(event -> isRelevant(event, attendees))
      .collect(Collectors.toList());

2020-09-10 16:04 UTC, omermadmon commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +      for (Event event : events) {
That's super cool, I'll use it more!

2020-09-10 16:05 UTC, merged